module.exports = {

	extends: "eslint:recommended",

	parser: "babel-eslint",

	parserOptions: {
		ecmaVersion: 2017,
		ecmaFeatures: {
			classes: true
		}
	},

	plugins: [
		"chai-expect"
	],

	rules: {
		"array-bracket-newline": ["error", { "multiline": true }],
		"array-bracket-spacing": "error",
		"arrow-parens": ["error", "as-needed"],
		"arrow-spacing": "error",
		"block-scoped-var": "error",
		"block-spacing": "error",
		"brace-style": "error",
		"complexity": "error",
		"consistent-return": "error",
		"curly": "error",
		"default-case": "error",
		"capitalized-comments": ["error", "always", {"ignoreConsecutiveComments": true}],
		"comma-spacing": ["error", { "before": false, "after": true }],
		"comma-style": "error",
		"dot-notation": "error",
		"eol-last": "error",
		"eqeqeq": "error",
		"func-call-spacing": "error",
		"func-names": "error",
		"func-style": ["error", "declaration", {"allowArrowFunctions": true}],
		"global-require": "error",
		"indent": ["error", "tab"],
		"jsx-quotes": "error",
		"key-spacing": "error",
		"keyword-spacing": "error",
		"line-comment-position": "error",
		"linebreak-style": "error",
		"lines-around-comment": "error",
		"max-depth": "warn",
		"max-lines": "warn",
		"max-params": "warn",
		"max-statements": "warn",
		"max-statements-per-line": "warn",
		"new-parens": "error",
		"no-catch-shadow": "error",
		"no-confusing-arrow": "error",
		"no-console": "off",
		"no-duplicate-imports": "error",
		"no-else-return": "error",
		"no-empty-function": "error",
		"no-extra-bind": "error",
		"no-extra-parens": "error",
		"no-implicit-coercion": "error",
		"no-implicit-globals": "error",
		"no-implied-eval": "error",
		"no-inline-comments": "error",
		"no-invalid-this": "error",
		"no-irregular-whitespace": "error",
		"no-lone-blocks": "error",
		"no-lonely-if": "error",
		"no-loop-func": "error",
		"no-mixed-operators": "error",
		"no-multi-assign": "error",
		"no-multi-spaces": "error",
		"no-nested-ternary": "error",
		"no-new-func": "error",
		"no-new-wrappers": "error",
		"no-param-reassign": "error",
		"no-return-assign": "error",
		"no-return-await": "error",
		"no-self-compare": "error",
		"no-sequences": "error",
		"no-shadow": "error",
		"no-shadow-restricted-names": "error",
		"no-template-curly-in-string": "error",
		"no-throw-literal": "error",
		"no-trailing-spaces": "error",
		"no-unmodified-loop-condition": "error",
		"no-unneeded-ternary": "error",
		"no-unused-expressions": "error",
		"no-use-before-define": "error",
		"no-useless-call": "error",
		"no-useless-computed-key": "error",
		"no-useless-concat": "error",
		"no-useless-constructor": "error",
		"no-useless-rename": "error",
		"no-useless-return": "error",
		"no-var": "error",
		"no-void": "error",
		"no-whitespace-before-property": "error",
		"nonblock-statement-body-position": "error",
		"object-curly-newline": ["error", {"consistent": true}],
		"object-curly-spacing": "error",
		"object-property-newline": "error",
		"operator-assignment": "error",
		"operator-linebreak": ["error", "after"],
		"padded-blocks": ["error", "never"],
		"prefer-const": "error",
		"prefer-promise-reject-errors": "error",
		"prefer-spread": "error",
		"prefer-template": "error",
		"quote-props": ["error", "as-needed"],
		"quotes": ["error", "single"],
		"rest-spread-spacing": "error",
		"semi": "error",
		"semi-spacing": "error",
		"semi-style": "error",
		"sort-imports": "error",
		"sort-keys": "error",
		"sort-vars": "error",
		"space-before-blocks": "error",
		"space-before-function-paren": ["error", "never"],
		"space-in-parens": "error",
		"space-infix-ops": "error",
		"space-unary-ops": "error",
		"spaced-comment": "error",
		"switch-colon-spacing": "error",
		"template-curly-spacing": "error",
		"wrap-regex": "error",
		"strict": "error",
		"valid-jsdoc": "error",
		"wrap-iife": "error",
		"yield-star-spacing": "error",

		"chai-expect/missing-assertion": "error",
		"chai-expect/no-inner-compare": "error",
		"chai-expect/terminating-properties": "error",
	},

};
